config/routes.rb
Rails.application.routes.draw do
  mount RedactorRails::Engine => '/redactor_rails'
  resources :media

  resources :schedule, only: :create
  ActiveAdmin.routes(self)

  resources :schedule, only: :create

  resources :pitches do
    member do
      put "like", to: "pitches#upvote"
      put "dislike", to: "pitches#downvote"
      put "mail_user", to: "pitches#send_final_work_mail", as: 'mail_user'
    end
    resources :comments
end
  
  root to: 'pitches#index'
  #devise_for :users
  devise_for :users, controllers: { sessions: "users/sessions" }
  resources :users
  get  '/users/sign_up(.:format)', to:'devise_invitable/registrations#new', as:'signup'

  get  '/users/sign_in(.:format)', to:'devise/sessions#new', as:'login'

  get  '/about', to:'pages#about', as:'about'


end

app/models/pitch.rb
class Pitch < ActiveRecord::Base
  validates :name, :media_type_id, :category_id, :description, :presence => true
  acts_as_votable

  belongs_to :user
  belongs_to :category
  belongs_to :media_type
  has_many :comments

def self.top_voted
  self.all.sort_by{|a| - a.get_upvotes.size }
end
  # def self.media_types
  #   ["Video","Audio","Written"]
  # end

  # def self.categories
  #   ["Arts","Sports","Politics","Current Events","Education","Entertainment"]
  # end

end

app/controllers/pitches_controller.rb
class PitchesController < ApplicationController
  require 'will_paginate/array' 
  before_action :set_pitch, only: [:show, :edit, :update, :destroy , :send_final_work_mail]
  before_action :set_categories_media_types, only: [:edit, :new, :update, :create]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authorized_user, only: [:edit, :update, :destroy]

  # GET /pitches
  # GET /pitches.json
  def index
    if flash.key? :notice
      flash.now[:notice] = flash[:notice].html_safe
      flash.now[:notice] += "<br/>".html_safe
      flash.now[:notice] += "Current iteration ends on #{Schedule.iter_end.to_formatted_s(:long)}"
    else
      flash.now[:notice] = "Current iteration ends on #{Schedule.iter_end.to_formatted_s(:long)}".html_safe
    end

    sort = params[:sort] || session[:sort] || "recent"
    session[:sort] = sort
    if (sort=="recent") 
      @pitches = Pitch.order(created_at: :desc)
    else
      @pitches = Pitch.all.sort_by{|a| - a.get_upvotes.size }
  end
  @pitches = @pitches.paginate(:page => params[:page] || 1, :per_page => 30)

end

  # GET /pitches/1
  # GET /pitches/1.json
  def show
  end

  # GET /pitches/new
  def new
    @pitch = current_user.pitches.build
  end

  # GET /pitches/1/edit
  def edit
  end

  # POST /pitches
  # POST /pitches.json
  def create
    @pitch = current_user.pitches.build(pitch_params)

    if @pitch.save
      flash[:notice] = "Pitch was successfully created."
      redirect_to pitches_path
    else
      render :new
    end
  end

  # PATCH/PUT /pitches/1
  # PATCH/PUT /pitches/1.json
  def update
    if @pitch.update(pitch_params)
      flash[:notice] = 'Pitch was successfully updated.'
      redirect_to pitch_path(@pitch)
    else
      render :edit
    end
  end

  # DELETE /pitches/1
  # DELETE /pitches/1.json
  def destroy
    @pitch.destroy
    redirect_to pitches_path, :notice => 'Pitch was successfully destroyed.'
  end

  def upvote
    @pitch = Pitch.find(params[:id])
    if @pitch.created_at > Schedule.iter_start
      @pitch.upvote_by current_user
    else
      flash[:notice] = "Cannot vote on previous iteration's pitches."
    end

    redirect_to :back
  end

  def downvote
    @pitch = Pitch.find(params[:id])

    if current_user.voted_up_on?(@pitch)
      if @pitch.created_at > Schedule.iter_start
        @pitch.downvote_by current_user
      else
        flash[:notice] = "Cannot vote on previous iteration's pitches."
      end
    end

    redirect_to :back
  end

  def send_final_work_mail
    UserMailer.submit_final_work(@pitch).deliver_now
    flash[:success] = 'Sent successfully.'
    redirect_to :back
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_pitch
      @pitch = Pitch.find(params[:id])
    end
    def set_categories_media_types
      @categories = Category.categories_list
      @media_types = MediaType.all.map { |m| [m.name,m.id] }
    end
    def authorized_user
      @pitch = current_user.pitches.find_by(id: params[:id])
      redirect_to pitches_path, notice: "Not authorized to edit this pitch" if @pitch.nil?
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def pitch_params
      params.require(:pitch).permit(:name, :media_type_id,  :description, :page,:category_id)
    end
  end

app/helpers/pitches_helper.rb
module PitchesHelper
end

app/views/pitches/_form.html.haml
= simple_form_for @pitch, :html => { :class => 'form-horizontal' } do |f|
  %fieldset
    = render 'shared/errors', obj: @pitch
    .form-group
      = f.label :name,class: "col-sm-2 control-label"
      .col-sm-6
        = f.text_field :name, :class => "form-control" 
    .form-group
      = f.label :media_type_id,class: "col-sm-2 control-label"
      .col-sm-6
        = f.select :media_type_id , @media_types, :class => "form-control"
    .form-group
      = f.label :category_id,class: "col-sm-2 control-label"
      .col-sm-6
        = f.select :category_id, @categories , :class => "form-control" 
    .form-group
      = f.label :description,class: "col-sm-2 control-label"
      .col-sm-6
        = f.text_area :description,size: "60x6", :class => "form-control" 
  .form-actions
    .col-sm-6.col-sm-offset-2
      = f.submit  'Submit/Update Pitch', :class => 'btn btn-primary'
      = link_to t('.cancel', :default => t("helpers.links.cancel")), pitches_path, :class => 'btn'

app/views/pitches/edit.html.haml
%h1 Editing pitch

= render 'form'

= link_to 'Show', @pitch
\|
= link_to 'Back', pitches_path

app/views/pitches/index.html.haml
.list-group#pitches-list
  .btn-group
    = link_to_if(session[:sort] != "recent", "Most Recent", { action: "index", sort: "recent" }, id: "most-recent")
    = link_to_if(session[:sort] != "top", "Top Voted", { action: "index", sort: "top" },id: "top-voted")
  %br
  - @pitches.each do |pitch|
    %li.list-group-item#pitch-item
      %blockquote
        = link_to pitch.name, pitch, :id => "pitch-link" 
        %small
          Submitted #{time_ago_in_words(pitch.created_at)} by 
          %cite 
            = link_to "#{pitch.user.name}", user_path(pitch.user)
      %p.lead
        #{pitch.description}
      %cite
        #{pitch.category.name}, #{pitch.media_type.name}
      -if not @disc_disabled
        %br/
        .btn-group
          = link_to like_pitch_path(pitch), method: :put, id: ("vote-up" << pitch.id.to_s) do
            .btn-group
              .fa.fa-thumbs-up.fa-lg.icon-success
              .badge#num-voteup
                \#{pitch.get_upvotes.size}
          - if user_signed_in? && current_user.voted_up_on?(pitch)
            = link_to dislike_pitch_path(pitch),  method: :put, id: ("vote-down" << pitch.id.to_s) do
              .btn-group
                .fa.fa-thumbs-down.fa-lg.icon-danger
        .active.pull-right
          %span.badge
            = pitch.comments.count
          = link_to "Comments", pitch
  = will_paginate @pitches
     

app/views/pitches/new.html.haml
- model_class = Pitch
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/pitches/search.html.haml
<h2>Search Results</h2>

-if @found_pitch.empty?
  <p>No results found. </p>

%table
  %thead
    %tr
      %th Name
      %th Media
      %th Category
      %th Text
      %th
      %th
      %th

  %tbody
    - @found_pitch.each do |pitch|
      %tr
        %td= pitch.name
        %td= pitch.media
        %td= pitch.category
        %td= pitch.text

app/views/pitches/show.html.haml
%p#notice
.page-header
	%blockquote
		%h3
			= @pitch.name
		%small
			Submitted by 
			=link_to "#{@pitch.user.name}",user_path(@pitch.user)
	%h4
		= @pitch.description
	%br/
	%cite
		#{@pitch.media_type.name}, #{@pitch.category.name}
.btn-group
	= link_to like_pitch_path(@pitch), method: :put do
		.btn-group
			.fa.fa-thumbs-up.fa-2x.icon-success
			%span.badge
				\#{@pitch.get_upvotes.size}
	- if user_signed_in? && current_user.voted_up_on?(@pitch)
		= link_to dislike_pitch_path(@pitch),  method: :put do
			.btn-group
				.fa.fa-thumbs-down.fa-2x.icon-danger
- if @pitch.user == current_user
	.btn-group.pull-right
		= link_to 'Back', pitches_path,  class: "btn btn-info"
		= link_to 'Edit', edit_pitch_path(@pitch), class: "btn btn-info"
		= link_to 'Remove', @pitch, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"
.active
	%h4/
	Comments
%br/
#comments
	= render :partial => @pitch.comments
= simple_form_for [@pitch, Comment.new]  do |f|
	.field
	= f.text_area :body, class: "form-control"
	%br/
	= f.submit "Add Comment", class: "btn btn-primary"