config/routes.rb
Rails.application.routes.draw do
  mount RedactorRails::Engine => '/redactor_rails'
  resources :media

  resources :schedule, only: :create
  ActiveAdmin.routes(self)

  resources :schedule, only: :create

  resources :pitches do
    member do
      put "like", to: "pitches#upvote"
      put "dislike", to: "pitches#downvote"
      put "mail_user", to: "pitches#send_final_work_mail", as: 'mail_user'
    end
    resources :comments
end
  
  root to: 'pitches#index'
  #devise_for :users
  devise_for :users, controllers: { sessions: "users/sessions" }
  resources :users
  get  '/users/sign_up(.:format)', to:'devise_invitable/registrations#new', as:'signup'

  get  '/users/sign_in(.:format)', to:'devise/sessions#new', as:'login'

  get  '/about', to:'pages#about', as:'about'


end

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    %a{:href => "/"} Home
  %nav
    %ul
      %li= link_to "About", about_path

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "col-md-9 alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      //%button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-inverse{role: "navigation"}
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-2", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to (image_tag("logo-6.png", :alt => "YouthZone Del Norte", :width => 350, :height => 100)), root_path #, class: 'navbar-brand'
    %br
    %br
    %br
    #bs-example-navbar-collapse-2.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
  <li><%= link_to 'Pitches', pitches_path %></li>
  <li><%= link_to 'PITCH', new_pitch_path %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.admin? %>
    <li><%= link_to 'Admin', '/admin' %></li>
    <li><%= link_to 'Users', users_path %></li>
  <% end %>
<% end %>

app/views/layouts/_navigation_links.html.haml
- if user_signed_in?
  - if current_user.admin?
    %li= link_to 'Admin', '/admin'
    %li= link_to 'Users', users_path
    %li= link_to 'Final Work', media_path
- if user_signed_in?
  %li= link_to 'Submit Pitch', new_pitch_path
  %li= link_to 'Account', edit_user_registration_path
  %li{:id => 'signoutButton'}= link_to 'Sign out', destroy_user_session_path, :method=>'delete'
- else
  %li= link_to 'Sign in', new_user_session_path
  %li= link_to 'Sign up', new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'YouthZone Del Norte'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'YouthZone Del Norte'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      .bs-component
        = render 'layouts/navigation'
    #main_content.container
      = render 'layouts/messages'
      #container.col-md-9.center-block
        = yield
        = render 'layouts/footer'